name: Barani App on AWS
on:
  push:
    branches:
    - main
  
jobs:
  Build-App:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      - name: Barani CI/CD
        run:
          echo "We are Learning About Devop's Today"
      - name: Step 1
        run:
          echo "We are Learning About Devop's Today"
      - name: Step 2
        run:
          echo "We are Learning About Devop's Today"
      - name: Step 3
        run:
          echo "We are Learning About Devop's Today"
      - name: Step 4
        run:
          echo "We are Learning About Devop's Today"
